### ISSUE TITLE
Vault support [📣 FEEDBACK WANTED]

### ISSUE THREAD

**Issue by josemmo** [josemmo/yamipa#74]
Support for [Vault](https://dev.bukkit.org/projects/vault) and similar economy plugins might be a desirable feature to have in Yamipa, as shown by @ObcbO in #72. Multiple things have to be considered to add this feature properly.

**First**, how to specify the "prices". The best I can come up with is to add a section in the "config.yml" file with these properties:
```yml
# Prices for Vault-enabled servers
prices:
  download: 0.0  # Cost of downloading an image
  image: 0.0     # Cost of an image (deducted when placed, reimbursed when removed)
  item: 0.0      # Cost of creating an image item
```

By default (if omitted), no action has a cost to maintain backwards compatibility. Regarding the "prices.image" value it works like this:

- When a player places an image with `/yamipa place`, the amount will be deducted from his balance.
- When somebody removes an image with `/yamipa remove` or `/yamipa clear`, the image's owner will be reimbursed that amount.

The latter is problematic as, if the server owner changes "prices.image" to a higher value, it could be abused to generate more in-game currency by removing previously placed images. To fix this, the image price will need to be stored in "images.dat" alongside the rest of metadata.

**Second**, player feedback. Players need to be aware of how much it costs to perform a plugin action and when a given amount is substracted/reimbursed from their balance. Prompting for confirmation with every command execution is, IMO, way too much. So maybe adding an additional `/yamipa prices` command with the list of prices is the best solution.

This is, still, not ideal, as a dishonest server owner might use permissions to hide this command, leaving the players with no feedback.

---

Anyway, if anybody wants to give their opinion now's the time :)

- Should Vault support be added to Yamipa?
- Is this proposal reasonable?
- Is there a better way to give feedback to players?
- Am I missing something that should be taken into account?
